--245
--BY WXY 20081218
--元数据存储定义

--实体目录
CREATE TABLE XM_ENTITYDIR
(
	ID NUMBER(18) PRIMARY KEY,
	NAME VARCHAR2(255),
	CODE VARCHAR2(255),
	ALIAS VARCHAR2(255),
	STATUS NUMBER(5) DEFAULT 1,
	PARENTID NUMBER(18),
	CREATEDATE DATE,
	MODIFYDATE DATE,
	VERSIONINSTANCE NUMBER(18),
	COMMENTS VARCHAR2(255),
	VERSION NUMBER(15) DEFAULT 0 
);

CREATE SEQUENCE S_XM_ENTITYDIR;

ALTER TABLE XM_ENTITYDIR ADD FOREIGN KEY(PARENTID) REFERENCES XM_ENTITYDIR(ID);
ALTER TABLE XM_ENTITYDIR ADD FOREIGN KEY(VERSIONINSTANCE) REFERENCES X_VERSIONINSTANCE(ID);


--实体规格
CREATE TABLE XM_ENTITYSPEC
(
	ID NUMBER(18) PRIMARY KEY,
	NAME VARCHAR2(255),
	CODE VARCHAR2(255),
	ALIAS VARCHAR2(255),
	ENTITYDIRID NUMBER(18),
	PARENTID NUMBER(18),
	CORETABLENAME VARCHAR2(255),
	CTSEQUENCE VARCHAR2(255),	
	SATELLITETABLENAME VARCHAR2(255),
	STSEQUENCE VARCHAR2(255),	
	CLASSNAME VARCHAR2(255),
	ICONDIR VARCHAR2(255),
	STATUS NUMBER(5) DEFAULT 1,
	MAINTAININDICATOR NUMBER(5) DEFAULT 1,
	CREATEDATE DATE,
	MODIFYDATE DATE,
	VERSIONINSTANCE NUMBER(18),
	COMMENTS VARCHAR2(255),
	VERSION NUMBER(15) DEFAULT 0 
);

CREATE SEQUENCE S_XM_ENTITYSPEC;

ALTER TABLE XM_ENTITYSPEC ADD FOREIGN KEY(ENTITYDIRID) REFERENCES XM_ENTITYDIR(ID);
ALTER TABLE XM_ENTITYSPEC ADD FOREIGN KEY(PARENTID) REFERENCES XM_ENTITYSPEC(ID);
ALTER TABLE XM_ENTITYSPEC ADD FOREIGN KEY(VERSIONINSTANCE) REFERENCES X_VERSIONINSTANCE(ID);
	
--组件目录
CREATE TABLE XM_COMPONENTDIR
(
	ID NUMBER(18) PRIMARY KEY,
	NAME VARCHAR2(255),
	CODE VARCHAR2(255),
	ALIAS VARCHAR2(255),
	STATUS NUMBER(5) DEFAULT 1,
	PARENTID NUMBER(18),
	CREATEDATE DATE,
	MODIFYDATE DATE,
	VERSIONINSTANCE NUMBER(18),
	COMMENTS VARCHAR2(255),
	VERSION NUMBER(15) DEFAULT 0 
);

CREATE SEQUENCE S_XM_COMPONENTDIR;

ALTER TABLE XM_COMPONENTDIR ADD FOREIGN KEY(PARENTID) REFERENCES XM_COMPONENTDIR(ID);
ALTER TABLE XM_COMPONENTDIR ADD FOREIGN KEY(VERSIONINSTANCE) REFERENCES X_VERSIONINSTANCE(ID);

--组件规格
CREATE TABLE XM_COMPONENTSPEC
(
	ID NUMBER(18) PRIMARY KEY,
	NAME VARCHAR2(255),
	CODE VARCHAR2(255),
	ALIAS VARCHAR2(255),
	COMPONENTDIRID NUMBER(18),	
	COMPONENTTABLENAME VARCHAR2(255),
	SEQUENCE VARCHAR2(255),	
	PKNAME VARCHAR2(255),
	ICONDIR VARCHAR2(255),
	STATUS NUMBER(5) DEFAULT 1,
	MAINTAININDICATOR NUMBER(5) DEFAULT 1,
	CREATEDATE DATE,
	MODIFYDATE DATE,
	VERSIONINSTANCE NUMBER(18),
	COMMENTS VARCHAR2(255),
	VERSION NUMBER(15) DEFAULT 0 
);

CREATE SEQUENCE S_XM_COMPONENTSPEC;

ALTER TABLE XM_COMPONENTSPEC ADD FOREIGN KEY(COMPONENTDIRID) REFERENCES XM_COMPONENTDIR(ID);
ALTER TABLE XM_COMPONENTSPEC ADD FOREIGN KEY(VERSIONINSTANCE) REFERENCES X_VERSIONINSTANCE(ID);
	

--组件规格与基础实体定义约束表
CREATE TABLE XM_COMPSPECENTITYSPECASSIGN
(
	ID NUMBER(18) PRIMARY KEY,
	COMPONENTSPECID NUMBER(18),
	COMPONENTSPECVERSIONINSTANCE NUMBER(18),
	ENTITYSPECID NUMBER(18),
	COMMENTS NUMBER(18),
	VERSION NUMBER(15) DEFAULT 0
);

CREATE SEQUENCE S_XM_COMPSPECENTITYSPECASSIGN;

ALTER TABLE XM_COMPSPECENTITYSPECASSIGN ADD FOREIGN KEY(COMPONENTSPECID) REFERENCES XM_COMPONENTSPEC(ID);
ALTER TABLE XM_COMPSPECENTITYSPECASSIGN ADD FOREIGN KEY(COMPONENTSPECVERSIONINSTANCE) REFERENCES X_VERSIONINSTANCE(ID);
ALTER TABLE XM_COMPSPECENTITYSPECASSIGN ADD FOREIGN KEY(ENTITYSPECID) REFERENCES XM_ENTITYSPEC(ID);
				

--实体规格与组件规格的映射
CREATE TABLE XM_ENTITYSPEC2COMPONENTSPEC
(
	ID NUMBER(18) PRIMARY KEY,
	ENTITYSPECID NUMBER(18),
	ENTITYSPECVERSIONINSTANCE NUMBER(18),
	COMPONENTSPECID NUMBER(18),
	COMPONENTSPECVERSIONINSTANCE NUMBER(18),
	COMMENTS NUMBER(18),
	COMPONENTSPECALIAS VARCHAR2(255),
	STATUS NUMBER(5) DEFAULT 1,
	VERSION NUMBER(15) DEFAULT 0
);

CREATE SEQUENCE S_XM_ENTITYSPEC2COMPONENTSPEC;

ALTER TABLE XM_ENTITYSPEC2COMPONENTSPEC ADD FOREIGN KEY(ENTITYSPECID) REFERENCES XM_ENTITYSPEC(ID);
ALTER TABLE XM_ENTITYSPEC2COMPONENTSPEC ADD FOREIGN KEY(ENTITYSPECVERSIONINSTANCE) REFERENCES X_VERSIONINSTANCE(ID);
ALTER TABLE XM_ENTITYSPEC2COMPONENTSPEC ADD FOREIGN KEY(COMPONENTSPECID) REFERENCES XM_COMPONENTSPEC(ID);
ALTER TABLE XM_ENTITYSPEC2COMPONENTSPEC ADD FOREIGN KEY(COMPONENTSPECVERSIONINSTANCE) REFERENCES X_VERSIONINSTANCE(ID);


--组件实例
CREATE TABLE XM_COMPONENTINSTANCE
(
	ID NUMBER(18) PRIMARY KEY,
	ALIAS VARCHAR2(255),
	ENTITYSPECID NUMBER(18),
	ENTITYID NUMBER(18)
);

CREATE SEQUENCE S_XM_COMPONENTINSTANCE;
ALTER TABLE XM_COMPONENTINSTANCE ADD FOREIGN KEY(ENTITYSPECID) REFERENCES XM_ENTITYSPEC(ID);
	

--关系规格
CREATE TABLE XM_RELATIONSPEC
(
	ID NUMBER(18) PRIMARY KEY,
	NAME VARCHAR2(255),
	CODE VARCHAR2(255),
	RELATIONINSTANCETABLENAME VARCHAR2(255),
	MULTIPLE NUMBER(5) DEFAULT 0,	
	OWNERENTITYSPECID NUMBER(18),
	OWNERROLE VARCHAR2(255),
	SUPPLIERENTITYSPECID NUMBER(18),
	SUPPLIERROLE VARCHAR2(255),
	OWNERATTR NUMBER(18),
	SUPPLIERATTR NUMBER(18),
	VERSIONINSTANCEID NUMBER(18),
	VERSION NUMBER(15) DEFAULT 0
);

CREATE SEQUENCE S_XM_RELATIONSPEC;

ALTER TABLE XM_RELATIONSPEC ADD FOREIGN KEY(OWNERENTITYSPECID) REFERENCES XM_ENTITYSPEC(ID);
ALTER TABLE XM_RELATIONSPEC ADD FOREIGN KEY(SUPPLIERENTITYSPECID) REFERENCES XM_ENTITYSPEC(ID);

--关系实例
CREATE TABLE XM_RELATIONINSTANCE
(
	ID NUMBER(18) PRIMARY KEY,
	RELATIONSPECID NUMBER(18),
	OWNERID NUMBER(18),
	SUPPLIERID NUMBER(18),
	VERSION NUMBER(15) DEFAULT 0
);

CREATE SEQUENCE S_XM_RELATIONINSTANCE;

ALTER TABLE XM_RELATIONINSTANCE ADD FOREIGN KEY(RELATIONSPECID) REFERENCES XM_RELATIONSPEC(ID);


--实体规格与关系规格的映射
CREATE TABLE XM_ENTITYSPEC2RELATIONSPEC
(
	ID NUMBER(18) PRIMARY KEY,
	ENTITYSPECID NUMBER(18),
	ENTITYSPECVERSIONINSTANCE NUMBER(18),
	RELATIONSPECID NUMBER(18),
	RELATIONSPECVERSIONINSTANCE NUMBER(18),
	STATUS NUMBER(5) DEFAULT 1,
	COMMENTS NUMBER(18),
	VERSION NUMBER(15) DEFAULT 0
);

CREATE SEQUENCE S_XM_ENTITYSPEC2RELATIONSPEC;

ALTER TABLE XM_ENTITYSPEC2RELATIONSPEC ADD FOREIGN KEY(ENTITYSPECID) REFERENCES XM_ENTITYSPEC(ID);
ALTER TABLE XM_ENTITYSPEC2RELATIONSPEC ADD FOREIGN KEY(ENTITYSPECVERSIONINSTANCE) REFERENCES X_VERSIONINSTANCE(ID);
ALTER TABLE XM_ENTITYSPEC2RELATIONSPEC ADD FOREIGN KEY(RELATIONSPECID) REFERENCES XM_RELATIONSPEC(ID);
ALTER TABLE XM_ENTITYSPEC2RELATIONSPEC ADD FOREIGN KEY(RELATIONSPECVERSIONINSTANCE) REFERENCES X_VERSIONINSTANCE(ID);


--实体定义
CREATE TABLE XM_ENTITYDESCRIPTOR
(
	ID NUMBER(18) PRIMARY KEY,
	ENTITYSPECID NUMBER(18),
	ENTITYSPECVERSIONINSTANCE NUMBER(18),
	COLUMNNAME VARCHAR2(255),
	COLUMNTYPE NUMBER(5) DEFAULT 0,
	ATTRNAME VARCHAR2(255),
	ATTRDISPNAME VARCHAR2(255),
	DATATYPE NUMBER(5) DEFAULT 0,
	DATALENGTH NUMBER(15),
	ISPK NUMBER(5) DEFAULT 0,
	ISFK NUMBER(5) DEFAULT 0,
	ISVERSION NUMBER(5) DEFAULT 0,
	VERSION NUMBER(15) DEFAULT 0
);

CREATE SEQUENCE S_XM_ENTITYDESCRIPTOR;

ALTER TABLE XM_ENTITYDESCRIPTOR ADD FOREIGN KEY(ENTITYSPECID) REFERENCES XM_ENTITYSPEC(ID);
ALTER TABLE XM_ENTITYDESCRIPTOR ADD FOREIGN KEY(ENTITYSPECVERSIONINSTANCE) REFERENCES X_VERSIONINSTANCE(ID);


--组件实体定义
CREATE TABLE XM_COMPONENTDESCRIPTOR
(
	ID NUMBER(18) PRIMARY KEY,
	COMPONENTSPECID NUMBER(18),
	COMPONENTVERSIONINSTANCE NUMBER(18),
	COLUMNNAME VARCHAR2(255),
	COLUMNTYPE NUMBER(5) DEFAULT 0,
	ATTRNAME VARCHAR2(255),
	ATTRDISPNAME VARCHAR2(255),
	DATATYPE NUMBER(5) DEFAULT 0,
	DATALENGTH NUMBER(15),
	ISPK NUMBER(5) DEFAULT 0,
	ISFK NUMBER(5) DEFAULT 0,
	ISVERSION NUMBER(5) DEFAULT 0,
	VERSION NUMBER(15) DEFAULT 0
);

CREATE SEQUENCE S_XM_COMPONENTDESCRIPTOR;

ALTER TABLE XM_COMPONENTDESCRIPTOR ADD FOREIGN KEY(COMPONENTSPECID) REFERENCES XM_COMPONENTSPEC(ID);
ALTER TABLE XM_COMPONENTDESCRIPTOR ADD FOREIGN KEY(COMPONENTVERSIONINSTANCE) REFERENCES X_VERSIONINSTANCE(ID);

--by wxy 20081226
ALTER TABLE XM_ENTITYSPEC2RELATIONSPEC ADD CASCADEDELETE NUMBER(5) DEFAULT 2;

ALTER TABLE XM_COMPSPECENTITYSPECASSIGN ADD ENTITYSPECVERSIONINSTANCE NUMBER(18);
ALTER TABLE XM_COMPSPECENTITYSPECASSIGN ADD FOREIGN KEY(ENTITYSPECVERSIONINSTANCE) REFERENCES X_VERSIONINSTANCE(ID);

ALTER TABLE XM_RELATIONSPEC MODIFY OWNERATTR VARCHAR2(255);
ALTER TABLE XM_RELATIONSPEC MODIFY SUPPLIERATTR VARCHAR2(255);

--by wxy 20090106
ALTER TABLE XM_ENTITYSPEC ADD INDICATORCOLUMNNAME VARCHAR2(255);
ALTER TABLE XM_ENTITYSPEC ADD INDICATORCOLUMNVALUE VARCHAR2(255);


--实体管理模板
CREATE TABLE XM_ENTITYMGTTEMPLATE
(
	ID NUMBER(18) PRIMARY KEY,
	NAME VARCHAR2(255),
	CODE VARCHAR2(255),
	ALIAS VARCHAR2(255),	
	ENTITYMGTRULEID NUMBER(18),	
	ENTITYSPECID NUMBER(18),	
	ENTITYSPECVERSIONINSTANCE NUMBER(18),
	LOCATIONID NUMBER(18),	
	STATUS NUMBER(5) DEFAULT 1,	
	CREATEDATE DATE,
	MODIFYDATE DATE,	
	COMMENTS VARCHAR2(255),
	VERSION NUMBER(15) DEFAULT 0 
);

CREATE SEQUENCE S_XM_ENTITYMGTTEMPLATE;

ALTER TABLE XM_ENTITYMGTTEMPLATE ADD FOREIGN KEY(ENTITYSPECID) REFERENCES XM_ENTITYSPEC(ID);
ALTER TABLE XM_ENTITYMGTTEMPLATE ADD FOREIGN KEY(ENTITYSPECVERSIONINSTANCE) REFERENCES X_VERSIONINSTANCE(ID);
--ALTER TABLE XM_ENTITYMGTTEMPLATE ADD FOREIGN KEY(LOCATIONID) REFERENCES X_LOCATION(ID);


--实体访问路径
CREATE TABLE XM_ENTITYACCESSURL
(
	ID NUMBER(18) PRIMARY KEY,
	NAME VARCHAR2(255),
	CODE VARCHAR2(255),
	ALIAS VARCHAR2(255),
	OPEREATIONTYPE NUMBER(5) DEFAULT 7,
	ENTITYMGTTEMPLATEID NUMBER(18),	
	PERMISSIONS VARCHAR2(255),	
	STATUS NUMBER(5) DEFAULT 1,	
	CREATEDATE DATE,
	MODIFYDATE DATE,	
	COMMENTS VARCHAR2(255),
	VERSION NUMBER(15) DEFAULT 0 
);

CREATE SEQUENCE S_XM_ENTITYACCESSURL;

ALTER TABLE XM_ENTITYACCESSURL ADD FOREIGN KEY(ENTITYMGTTEMPLATEID) REFERENCES XM_ENTITYMGTTEMPLATE(ID);


--实体管理模板属性
CREATE TABLE XM_ENTITYMGTTEMPLATEATTR
(
	ID NUMBER(18) PRIMARY KEY,
	ENTITYMGTTEMPLATEID NUMBER(18),	
	INDICATOR NUMBER(5) DEFAULT 7,
	ATTRIBUTEID NUMBER(18), 
	SEQNO NUMBER(15) DEFAULT 0, 
	ISVISIBLE NUMBER(5) DEFAULT 1,
	ISEDITABLE NUMBER(5) DEFAULT 2,
	ISNULL NUMBER(5) DEFAULT 1,
	ISSORTABLE NUMBER(5) DEFAULT 2,
	UICOMPONENTSTYLE NUMBER(5) DEFAULT 1,
	UICOMPONENTTYPE NUMBER(5) DEFAULT 4,	
	DICCLASSNAME VARCHAR2(255),
	DICATTRIBUTENAME VARCHAR2(255),
	DICDEFAULTVALUE NUMBER(5) DEFAULT 1,		
	STATUS NUMBER(5) DEFAULT 1,	
	CREATEDATE DATE,
	MODIFYDATE DATE,	
	COMMENTS VARCHAR2(255),
	VERSION NUMBER(15) DEFAULT 0 
);

CREATE SEQUENCE S_XM_ENTITYMGTTEMPLATEATTR;

--实体管理模板关系
CREATE TABLE XM_ENTITYMGTTEMPLATERELATION
(
	ID NUMBER(18) PRIMARY KEY,
	ENTITYMGTTEMPLATEID NUMBER(18),	
	RELATIONSPECID NUMBER(18),	
	NAME VARCHAR2(255),
	DISPNAME VARCHAR2(255),
	SEQNO NUMBER(15) DEFAULT 0,
	ENABLECREATE NUMBER(5) DEFAULT 1,
	ENABLEMODIFY NUMBER(5) DEFAULT 1,
	ENABLEDELETE NUMBER(5) DEFAULT 1,
	LOADMODE NUMBER(5) DEFAULT 1,
	DISPMODE NUMBER(5) DEFAULT 1,
	RELADISPMGTTEMPLATEID NUMBER(18),	
	RELACREATEMGTTEMPLATEID NUMBER(18),	
	RELAMODIFYMGTTEMPLATEID NUMBER(18),	
	STATUS NUMBER(5) DEFAULT 1,	
	CREATEDATE DATE,
	MODIFYDATE DATE,	
	COMMENTS VARCHAR2(255),
	VERSION NUMBER(15) DEFAULT 0 
);

CREATE SEQUENCE S_XM_ENTITYMGTTEMPLATERELATION;

ALTER TABLE XM_ENTITYMGTTEMPLATERELATION ADD FOREIGN KEY(ENTITYMGTTEMPLATEID) REFERENCES XM_ENTITYMGTTEMPLATE(ID);
ALTER TABLE XM_ENTITYMGTTEMPLATERELATION ADD FOREIGN KEY(RELATIONSPECID) REFERENCES XM_RELATIONSPEC(ID);
ALTER TABLE XM_ENTITYMGTTEMPLATERELATION ADD FOREIGN KEY(RELADISPMGTTEMPLATEID) REFERENCES XM_ENTITYMGTTEMPLATE(ID);
ALTER TABLE XM_ENTITYMGTTEMPLATERELATION ADD FOREIGN KEY(RELACREATEMGTTEMPLATEID) REFERENCES XM_ENTITYMGTTEMPLATE(ID);
ALTER TABLE XM_ENTITYMGTTEMPLATERELATION ADD FOREIGN KEY(RELAMODIFYMGTTEMPLATEID) REFERENCES XM_ENTITYMGTTEMPLATE(ID);


--by wxy 20090113
ALTER TABLE XM_ENTITYSPEC ADD DATASOURCE NUMBER(5) DEFAULT 1;

ALTER TABLE XM_ENTITYSPEC2COMPONENTSPEC ADD MAINTENACEINDICATOR NUMBER(5) DEFAULT 1;

ALTER TABLE XM_ENTITYSPEC2RELATIONSPEC ADD MAINTENACEINDICATOR NUMBER(5) DEFAULT 1;

ALTER TABLE XM_RELATIONSPEC RENAME COLUMN VERSIONINSTANCEID TO VERSIONINSTANCE;

ALTER TABLE XM_RELATIONSPEC ADD
(
 MAINTAININDICATOR NUMBER(5) DEFAULT 1,               
 CREATEDATE DATE,                       
 MODIFYDATE DATE, 
 COMMENTS VARCHAR2(255)     
);

ALTER TABLE XM_ENTITYDESCRIPTOR ADD DATAPERCISION NUMBER(15) DEFAULT 0;

ALTER TABLE XM_COMPONENTDESCRIPTOR ADD DATAPERCISION NUMBER(15) DEFAULT 0;

--by wxy 20090109
ALTER TABLE XM_RELATIONSPEC ADD STATUS NUMBER(5) DEFAULT 1;
ALTER TABLE XM_COMPONENTDESCRIPTOR ADD STATUS NUMBER(5) DEFAULT 1;
ALTER TABLE XM_COMPONENTDESCRIPTOR ADD MAINTAININDICATOR NUMBER(5) DEFAULT 1;

ALTER TABLE XM_COMPSPECENTITYSPECASSIGN RENAME TO XM_COMPSPECENTITYSPECRESTRICT;

ALTER TABLE XM_COMPSPECENTITYSPECRESTRICT DROP (COMPONENTSPECVERSIONINSTANCE);
ALTER TABLE XM_COMPSPECENTITYSPECRESTRICT DROP (ENTITYSPECVERSIONINSTANCE);


--by wxy 20090202
exec dropforeignkey('XM_ENTITYACCESSURL','ENTITYMGTTEMPLATEID');

drop table XM_ENTITYMGTTEMPLATE;
drop table XM_ENTITYMGTTEMPLATEATTR;
drop table XM_APMGTTLASSOC;
drop table XM_ACCESSURL;
drop table XM_ENTITYLAYOUTTEMPLATE;
drop table XM_ENTITYLAYOUTTEMPLATEATTR;
drop table XM_ENTITYLAYOUTTLRELATION;

create table XM_ENTITYMGTTEMPLATE
(
  ID                        NUMBER(18) primary key,
  NAME                      VARCHAR2(255),
  CODE                      VARCHAR2(255),
  ALIAS                     VARCHAR2(255),  
  ENTITYSPECID              NUMBER(18),
  ENTITYSPECVERSIONINSTANCE NUMBER(18),
  LOCATIONID                NUMBER(18),
  STATUS                    NUMBER(5) default 1,
  CREATEDATE                DATE,
  MODIFYDATE                DATE,
  COMMENTS                  VARCHAR2(255),
  VERSION                   NUMBER(15) default 0
);

create sequence S_XM_ENTITYMGTTEMPLATE;

ALTER TABLE XM_ENTITYMGTTEMPLATE ADD FOREIGN KEY(ENTITYSPECID) REFERENCES XM_ENTITYSPEC(ID);
ALTER TABLE XM_ENTITYMGTTEMPLATE ADD FOREIGN KEY(ENTITYSPECVERSIONINSTANCE) REFERENCES X_VERSIONINSTANCE(ID);
--ALTER TABLE XM_ENTITYMGTTEMPLATE ADD FOREIGN KEY(LOCATIONID) REFERENCES X_LOCATION(ID);


create table XM_ENTITYMGTTEMPLATEATTR
(
  ID                  NUMBER(18) primary key,
  ENTITYMGTTEMPLATEID NUMBER(18),
  INDICATOR           NUMBER(5) default 1,
  ATTRIBUTEID         NUMBER(18),
  POLICYRULEID        NUMBER(18),
  STATUS              NUMBER(5) default 1,
  CREATEDATE          DATE,
  MODIFYDATE          DATE,
  COMMENTS            VARCHAR2(255),
  VERSION             NUMBER(15) default 0
);

create sequence S_XM_ENTITYMGTTEMPLATEATTR;

ALTER TABLE XM_ENTITYMGTTEMPLATEATTR ADD FOREIGN KEY(ENTITYMGTTEMPLATEID) REFERENCES XM_ENTITYMGTTEMPLATE(ID);
--ALTER TABLE XM_ENTITYMGTTEMPLATEATTR ADD FOREIGN KEY(POLICYRULEID) REFERENCES X_POLICYRULE(ID);


create table XM_APMGTTLASSOC
(
  ID                      NUMBER(18) primary key,
  MENUITEMID              NUMBER(18),
  ENTITYMGTTEMPLATEID     NUMBER(18),
  POLICYRULEID            NUMBER(18),  
  STATUS                  NUMBER(5) default 1,
  CREATEDATE              DATE,
  MODIFYDATE              DATE,
  COMMENTS                VARCHAR2(255),
  VERSION                 NUMBER(15) default 0
);

create sequence S_XM_APMGTTLASSOC;

ALTER TABLE XM_APMGTTLASSOC ADD FOREIGN KEY(MENUITEMID) REFERENCES X_MENUITEM(ID);
ALTER TABLE XM_APMGTTLASSOC ADD FOREIGN KEY(ENTITYMGTTEMPLATEID) REFERENCES XM_ENTITYMGTTEMPLATE(ID);
--ALTER TABLE XM_APMGTTLASSOC ADD FOREIGN KEY(POLICYRULEID) REFERENCES X_POLICYRULE(ID);


create table XM_ACCESSURL
(
  ID                  NUMBER(18) primary key,
  NAME                VARCHAR2(255),
  CODE                VARCHAR2(255),
  ALIAS               VARCHAR2(255),
  MENUITEMID   NUMBER(18),
  OPEREATIONTYPE      NUMBER(5) default 7,
  ENTITYMGTTEMPLATEID NUMBER(18),
  PERMISSIONS         VARCHAR2(255),
  STATUS              NUMBER(5) default 1,
  CREATEDATE          DATE,
  MODIFYDATE          DATE,
  COMMENTS            VARCHAR2(255),
  VERSION             NUMBER(15)
);

create sequence S_XM_ACCESSURL;

ALTER TABLE XM_ACCESSURL ADD FOREIGN KEY(MENUITEMID) REFERENCES X_MENUITEM(ID);
ALTER TABLE XM_ACCESSURL ADD FOREIGN KEY(ENTITYMGTTEMPLATEID) REFERENCES XM_ENTITYMGTTEMPLATE(ID);


create table XM_ENTITYLAYOUTTEMPLATE
(
  ID                        NUMBER(18) primary key,
  NAME                      VARCHAR2(255),
  CODE                      VARCHAR2(255),
  ALIAS                     VARCHAR2(255),
  ENTITYMGTTEMPLATEID       NUMBER(18),
  STYLE                     NUMBER(5) default 2,
  SPAN                      NUMBER(15),  
  STATUS                    NUMBER(5),
  CREATEDATE                DATE,
  MODIFYDATE                DATE,
  COMMENTS                  VARCHAR2(255),
  VERSION                   NUMBER(15) default 0
);

create sequence S_XM_ENTITYLAYOUTTEMPLATE;

ALTER TABLE XM_ENTITYLAYOUTTEMPLATE ADD FOREIGN KEY(ENTITYMGTTEMPLATEID) REFERENCES XM_ENTITYMGTTEMPLATE(ID);


create table XM_ENTITYLAYOUTTEMPLATEATTR
(
  ID                     NUMBER(18) primary key,
  ENTITYLAYOUTTEMPLATEID NUMBER(18),  
  SEQNO               NUMBER(15) default 0,
  ISVISIBLE           NUMBER(5) default 1,
  ISEDITABLE          NUMBER(5) default 2,
  ISNULL              NUMBER(5) default 1,
  ISSORTABLE          NUMBER(5) default 2,  
  UICOMPONENTTYPE     NUMBER(5) default 4,  
  STATUS              NUMBER(5),
  CREATEDATE          DATE,
  MODIFYDATE          DATE,
  COMMENTS            VARCHAR2(255),
  VERSION             NUMBER(15) default 0
);

create sequence S_XM_ENTITYLAYOUTTEMPLATEATTR;

ALTER TABLE XM_ENTITYLAYOUTTEMPLATEATTR ADD FOREIGN KEY(ENTITYLAYOUTTEMPLATEID) REFERENCES XM_ENTITYLAYOUTTEMPLATE(ID);


create table XM_ENTITYLAYOUTTLRELATION
(
  ID                      NUMBER(18) primary key,
  ENTITYLAYOUTTEMPLATEID  NUMBER(18),
  RELATIONSPECID          NUMBER(18),
  NAME                    VARCHAR2(255),
  DISPNAME                VARCHAR2(255),
  SEQNO                   NUMBER(15) default 0,
  ENABLECREATE            NUMBER(5) default 1,
  ENABLEMODIFY            NUMBER(5) default 1,
  ENABLEDELETE            NUMBER(5) default 1,
  LOADMODE                NUMBER(5) default 1,
  DISPMODE                NUMBER(5) default 1,
  RELADISPMGTTEMPLATEID   NUMBER(18),
  RELACREATEMGTTEMPLATEID NUMBER(18),
  RELAMODIFYMGTTEMPLATEID NUMBER(18),
  STATUS                  NUMBER(5) default 1,
  CREATEDATE              DATE,
  MODIFYDATE              DATE,
  COMMENTS                VARCHAR2(255),
  VERSION                 NUMBER(15) default 0
);

create sequence S_XM_ENTITYLAYOUTTLRELATION;

ALTER TABLE XM_ENTITYLAYOUTTLRELATION ADD FOREIGN KEY(ENTITYLAYOUTTEMPLATEID) REFERENCES XM_ENTITYLAYOUTTEMPLATE(ID);
ALTER TABLE XM_ENTITYLAYOUTTLRELATION ADD FOREIGN KEY(RELATIONSPECID) REFERENCES XM_RELATIONSPEC(ID);
ALTER TABLE XM_ENTITYLAYOUTTLRELATION ADD FOREIGN KEY(RELADISPMGTTEMPLATEID) REFERENCES XM_ENTITYMGTTEMPLATE(ID);
ALTER TABLE XM_ENTITYLAYOUTTLRELATION ADD FOREIGN KEY(RELACREATEMGTTEMPLATEID) REFERENCES XM_ENTITYMGTTEMPLATE(ID);
ALTER TABLE XM_ENTITYLAYOUTTLRELATION ADD FOREIGN KEY(RELAMODIFYMGTTEMPLATEID) REFERENCES XM_ENTITYMGTTEMPLATE(ID);


alter table XM_ENTITYDESCRIPTOR add
(
	DICCLASSNAME        VARCHAR2(255),
  DICATTRIBUTENAME    VARCHAR2(255),
  DICDEFAULTVALUE     NUMBER(5) default 0
);


alter table XM_COMPONENTDESCRIPTOR add
(
	DICCLASSNAME        VARCHAR2(255),
  DICATTRIBUTENAME    VARCHAR2(255),
  DICDEFAULTVALUE     NUMBER(5) default 0
);


ALTER TABLE XR_LOCATIONRELATIONINSTANCE ADD FOREIGN KEY (RELATIONSPECID) REFERENCES XM_RELATIONSPEC(ID);


INSERT INTO X_VERSIONINFO(ID,BUILDNO,EXECUTETIME,SCRIPTNAME,COMMENTS) 
    VALUES(S_X_VERSIONINFO.NEXTVAL,245,SYSDATE,'245-298','metadata module');
commit;
